### ISSUE TITLE
Present Basic Setups for WebStorm and VSCode

### ISSUE THREAD

**Issue by EagleoutIce** [Code-Inspect/flowr#442]
How to set up mocha test explorer (with filename and loader etc.)

As a sub section on the wiki, maybe as part of a new Contribution page?

**Comment by bjthehun** [comment]
@EagleoutIce Could you close this issue since it has been fixed with PR #664?

**Comment by EagleoutIce** [comment]
Yes! Sorry, normally i link them so they get closed automatically but this time i forgot!
