### ISSUE TITLE
[Bug]: Github Desktop does not work

### ISSUE THREAD

**Issue by Ehcsan** [Code-Inspect/flowr#485]
### What happened?

Commits and pushes cannot be done with Github Desktop.
Commits will be formated wrong and not accepted by the ci.
Pushes create issues with npm
![Screenshot 2023-11-07 171213](https://github.com/Code-Inspect/flowr/assets/68707578/2ab9220c-8f94-4647-a597-17dd12872fab)

### What version of R do you have installed?

4.3.1

### What version of flowR did you use?

1.3.2

### Meta Information

- [ ] The Issue is Urgent

**Comment by EagleoutIce** [comment]
Still not working, requires `npm.cmd` from the get-go
