### ISSUE TITLE
Should we move to "conventional commits"?

### ISSUE THREAD

**Issue by EagleoutIce** [Code-Inspect/flowr#513]
https://www.conventionalcommits.org/en/v1.0.0/.

What is your opinion @Ehcsan, @Core5563, @LukasPietzschmann?

**Comment by Ehcsan** [comment]
I would not be opposed to moving to „conventional commits“, however I think that we should incorperate the current commit standard (possibly under scope or footings). Potentially requiring the added clarity of the current standard.

**Comment by LukasPietzschmann** [comment]
Following a standard is, in my opinion, always a good thing. And as our current commit messages do not differ too drastically from "conventional commits", I am in favor of using the new standard.
