### ISSUE TITLE
Ensure xmlparsedata in ci test environment

### ISSUE THREAD

**Issue by EagleoutIce** [Code-Inspect/flowr#591]
At least the logs suggest hat it isn't present as the tests regularly prompt that it has to be installed.

**Comment by Ellpeck** [comment]
Would xmlparsedata need to be installed only for tests or should it be installed in general? thinking about whether this would make sense in [the setup action](https://github.com/Code-Inspect/flowr/blob/main/.github/actions/setup/action.yaml#L25), [the run workflow, maybe with additional inputs for added deps to be installed](https://github.com/Code-Inspect/flowr/blob/main/.github/workflows/run.yaml#L5), or each individual test workflow?

**Comment by EagleoutIce** [comment]
It should be present in essentially every CI environment :)
