### ISSUE TITLE
Persist history of flowR REPL sessions

### ISSUE THREAD

**Issue by EagleoutIce** [Code-Inspect/flowr#606]
If i reopen the repl in the same terminal session it would be nice to be able to reaccess the old history (e.g., when i recompile the flowR sources and want to check a command again).

**Comment by EagleoutIce** [comment]
This can be achieved, for example, with the help of an external file which persists the history.

For more information on the history, see <https://nodejs.org/api/readline.html#readlinepromisescreateinterfaceoptions>, the respective code is at: 
https://github.com/Code-Inspect/flowr/blob/75a417d913092e10cee2c27a251f9984ca35cf3b/src/cli/repl/core.ts#L23-L30

**Comment by EagleoutIce** [comment]
Example:

```shell
$ node dist/src/flowr.js 
R> :help
...
R> <up>
R> :help
<ctrl+c> <ctrl+c>

$ node dist/src/flowr.js 
R> <up>
R> :help
# in other words, :help is still in the history
```

With `<up>` referring to <kbd>↑</kbd> (i.e., the up arrow), and `<ctrl+c>` referring to <kbd>ctrl</kbd>+<kbd>c</kbd>

**Comment by Ellpeck** [comment]
Is there already a directory for persistent flowr data? I couldn't really find one on first try. If not, should it be like a local share / local app data sort of thing, or should it be stored with the executable?
