### ISSUE TITLE
Refactor: Avoid `async` when interfacing with the R shell

### ISSUE THREAD

**Issue by Ellpeck** [Code-Inspect/flowr#610]
Possibly implement some type of blocking/spinning wait system for waiting for the promise to be resolved on the main thread, rather than propagating `async` to dataflow etc.

This is to ease implementation and speed of #605

**Comment by Ellpeck** [comment]
@EagleoutIce Do you think this should be shell-specific, ie a layer above `RShell` along the lines of `SynchronounsRShell`, or should it be a generic system that can be used for any async code?

**Comment by EagleoutIce** [comment]
I would prefer a generic mechanism

**Comment by EagleoutIce** [comment]
Alternatively, we could make use of `spawnSync` for a one-off mechanims. I mean yes, spawning the R shell certainly has extra costs, but we only need it to do `xmlparsedata::xml_parse_data(parse(...))`. With this, collecting the output is much simpler as well. 

So we could redesign an `RShellSession` communication around this (e.g., by abstracting all command layers from the `RShell` for a new `RExecutionScript` - or whatever name fits better).

What is your opinion on this @Ellpeck?
