### ISSUE TITLE
Aww the Mermaid Markdown broke

### ISSUE THREAD

**Issue by EagleoutIce** [Code-Inspect/flowr#621]
![Screenshot_20240130_152432](https://github.com/Code-Inspect/flowr/assets/9303573/db80f798-b11a-48db-b01b-813286fe701b)

In https://github.com/Code-Inspect/flowr/wiki/Interface.

**Comment by bjthehun** [comment]
Apparently, GitHub support for Markdown in Mermaid broke, see:
https://github.com/orgs/community/discussions/106690

So this seems to be something only GitHub themselves can fix.

**Comment by EagleoutIce** [comment]
Uuuh, thank you very much for digging that up! So we probably just have to wait then :/ Thank you again!

**Comment by EagleoutIce** [comment]
This appears to be fixed now!
