### ISSUE TITLE
Add a startup configuration file for flowr

### ISSUE THREAD

**Issue by Ellpeck** [Code-Inspect/flowr#642]
Configuration files should be parsed from the current working directory or parent directories (?) as well as next to the executable (?)

Options we want to support:
- [x] allow disabling `source` parsing and analyzing (#605)

**Comment by EagleoutIce** [comment]
I would say: 
* move upwards the dir chain until a configuration is found 
* we only use the "closest" definition (maybe, later, we can talk about global defaults etc.)
* i think a json is easiest to implement
