### ISSUE TITLE
Fix Codecov Uploads

### ISSUE THREAD

**Issue by bjthehun** [Code-Inspect/flowr#737]
With #734, I also messed up the upload of code coverage results, as seen in this screenshot:

![Result for last QA run 1326](https://github.com/Code-Inspect/flowr/assets/38729215/92809478-e12b-479e-a334-920acb6ed5b4)

The upload silently fails (see the error below), without failing the QA workflow.

Because I feel that this is my fault, I would like someone else to fix this CI problem.

**Comment by EagleoutIce** [comment]
Thank you for reporting the Issue!

**Comment by Ellpeck** [comment]
It looks like this is just an issue of the codecov access token being missing, which is odd since I don't think you have access to change that to begin with. @EagleoutIce can you try generating a new one?
