### ISSUE TITLE
Assignment in every branch still reconstructs original assignment

### ISSUE THREAD

**Issue by Ellpeck** [Code-Inspect/flowr#802]
```R
x <- 1
if(x) {
  if(y) {
    x <- 3
  } else {
    x <- 2
  }
} else {
  x <- 4
}
print(x)
```

results in the first line (`x <- 1`) still being part of the slice, even though `x` is overwritten in every branch.

**Comment by EagleoutIce** [comment]
On a second look, this is the fault of the piece of code. 
the first condition `if(x)` causes `x <- 1` to be included.
Please re-insert the test as a part of #800, but modify the condition accordingly @Ellpeck.
