### ISSUE TITLE
Dataflow: dead code detection when returning in both if/else branches

### ISSUE THREAD

**Issue by Ellpeck** [Code-Inspect/flowr#816]
```ts
		assertDataflow(label('return in if',['name-normal', ...OperatorDatabase['<-'].capabilities, 'formals-named', 'newlines', 'numbers', ...OperatorDatabase['*'].capabilities, 'return', 'unnamed-arguments', 'if']),
			shell, `f <- function(x) {
   x <- 3 * x
   if(k)
      return(x)
   else
      return(1)
   x <- 2
   return(x)
}

f(5)`, emptyGraph())
```

produces [this Mermaid diagram]( https://mermaid.live/view#base64:eyJjb2RlIjoiJSUgZiA8LSBmdW5jdGlvbih4KSB7XG4lJSAgICB4IDwtIDMgKiB4XG4lJSAgICBpZihrKVxuJSUgICAgICAgcmV0dXJuKHgpXG4lJSAgICBlbHNlXG4lJSAgICAgICByZXR1cm4oMSlcbiUlICAgIHggPC0gMlxuJSUgICAgcmV0dXJuKHgpXG4lJSB9XG4lJSBcbiUlIGYoNSlcbiUlIFJvb3QgdmVydGljZXMgZGlmZmVyIGluIGdyYXBocy4gTW9yZSBpbiBnb3Q6IFszMCwwLDMxLDMzLDM1XVxuJSUgRGV0ZWN0ZWQgZGlmZmVyZW50IG51bWJlciBvZiB2ZXJ0aWNlcyEgZXhwZWN0ZWQgaGFzIDAsIGdvdCBoYXMgMjNcbiUlIERldGVjdGVkIGRpZmZlcmVudCBudW1iZXIgb2YgZWRnZXMhIGV4cGVjdGVkIGhhcyAwIChbXSkuIGdvdCBoYXMgMTggW1s4LFtbXCJidWlsdC1pblwiLHtcInR5cGVzXCI6MX1dLFs2LHtcInR5cGVzXCI6NjV9XSxbNyx7XCJ0eXBlc1wiOjY1fV1dXSxbNyxbWzEse1widHlwZXNcIjoxfV1dXSxbOSxbWzgse1widHlwZXNcIjo2NH1dLFs1LHtcInR5cGVzXCI6NzJ9XSxbXCJidWlsdC1pblwiLHtcInR5cGVzXCI6MX1dXV0sWzUsW1s4LHtcInR5cGVzXCI6Mn1dLFs5LHtcInR5cGVzXCI6Mn1dXV0sWzEyLFtbNSx7XCJ0eXBlc1wiOjF9XV1dLFsxNCxbWzEyLHtcInR5cGVzXCI6NzJ9XSxbXCJidWlsdC1pblwiLHtcInR5cGVzXCI6MX1dXV0sWzIxLFtbMTQse1widHlwZXNcIjo3Mn1dLFsxOSx7XCJ0eXBlc1wiOjcyfV0sWzEwLHtcInR5cGVzXCI6NjV9XSxbXCJidWlsdC1pblwiLHtcInR5cGVzXCI6MX1dXV0sWzE5LFtbMTcse1widHlwZXNcIjo3Mn1dLFtcImJ1aWx0LWluXCIse1widHlwZXNcIjoxfV1dXSxbMjQsW1syMyx7XCJ0eXBlc1wiOjY0fV0sWzIyLHtcInR5cGVzXCI6NzJ9XSxbXCJidWlsdC1pblwiLHtcInR5cGVzXCI6MX1dXV0sWzIyLFtbMjMse1widHlwZXNcIjoyfV0sWzI0LHtcInR5cGVzXCI6Mn1dXV0sWzI2LFtbNSx7XCJ0eXBlc1wiOjF9XSxbMjIse1widHlwZXNcIjoxfV1dXSxbMjgsW1syNix7XCJ0eXBlc1wiOjcyfV0sW1wiYnVpbHQtaW5cIix7XCJ0eXBlc1wiOjF9XV1dLFsyOSxbWzkse1widHlwZXNcIjo2NH1dLFsyMSx7XCJ0eXBlc1wiOjY0fV0sWzI0LHtcInR5cGVzXCI6NjR9XSxbMjgse1widHlwZXNcIjo3Mn1dLFsxNCx7XCJ0eXBlc1wiOjh9XSxbMTkse1widHlwZXNcIjo4fV0sW1wiYnVpbHQtaW5cIix7XCJ0eXBlc1wiOjF9XV1dLFszMSxbWzMwLHtcInR5cGVzXCI6NjR9XSxbMCx7XCJ0eXBlc1wiOjcyfV0sW1wiYnVpbHQtaW5cIix7XCJ0eXBlc1wiOjF9XV1dLFswLFtbMzAse1widHlwZXNcIjoyfV0sWzMxLHtcInR5cGVzXCI6Mn1dXV0sWzM1LFtbMzMse1widHlwZXNcIjo2NH1dLFswLHtcInR5cGVzXCI6MX1dLFsyOSx7XCJ0eXBlc1wiOjh9XSxbMzAse1widHlwZXNcIjo0fV1dXSxbMzMsW1sxLHtcInR5cGVzXCI6MTZ9XV1dLFsxLFtbMzMse1widHlwZXNcIjozMn1dXV1dXG4lJSBWZXJ0ZXggOCBoYXMgdW5kZWZpbmVkIG91dGdvaW5nIGVkZ2VzLiBleHBlY3RlZDogdW5kZWZpbmVkIHZzIGdvdDogW1tcImJ1aWx0LWluXCIse1widHlwZXNcIjoxfV0sWzYse1widHlwZXNcIjo2NX1dLFs3LHtcInR5cGVzXCI6NjV9XV1cbiUlIFZlcnRleCA3IGhhcyB1bmRlZmluZWQgb3V0Z29pbmcgZWRnZXMuIGV4cGVjdGVkOiB1bmRlZmluZWQgdnMgZ290OiBbWzEse1widHlwZXNcIjoxfV1dXG4lJSBWZXJ0ZXggOSBoYXMgdW5kZWZpbmVkIG91dGdvaW5nIGVkZ2VzLiBleHBlY3RlZDogdW5kZWZpbmVkIHZzIGdvdDogW1s4LHtcInR5cGVzXCI6NjR9XSxbNSx7XCJ0eXBlc1wiOjcyfV0sW1wiYnVpbHQtaW5cIix7XCJ0eXBlc1wiOjF9XV1cbiUlIFZlcnRleCA1IGhhcyB1bmRlZmluZWQgb3V0Z29pbmcgZWRnZXMuIGV4cGVjdGVkOiB1bmRlZmluZWQgdnMgZ290OiBbWzgse1widHlwZXNcIjoyfV0sWzkse1widHlwZXNcIjoyfV1dXG4lJSBWZXJ0ZXggMTIgaGFzIHVuZGVmaW5lZCBvdXRnb2luZyBlZGdlcy4gZXhwZWN0ZWQ6IHVuZGVmaW5lZCB2cyBnb3Q6IFtbNSx7XCJ0eXBlc1wiOjF9XV1cbiUlIFZlcnRleCAxNCBoYXMgdW5kZWZpbmVkIG91dGdvaW5nIGVkZ2VzLiBleHBlY3RlZDogdW5kZWZpbmVkIHZzIGdvdDogW1sxMix7XCJ0eXBlc1wiOjcyfV0sW1wiYnVpbHQtaW5cIix7XCJ0eXBlc1wiOjF9XV1cbiUlIFZlcnRleCAyMSBoYXMgdW5kZWZpbmVkIG91dGdvaW5nIGVkZ2VzLiBleHBlY3RlZDogdW5kZWZpbmVkIHZzIGdvdDogW1sxNCx7XCJ0eXBlc1wiOjcyfV0sWzE5LHtcInR5cGVzXCI6NzJ9XSxbMTAse1widHlwZXNcIjo2NX1dLFtcImJ1aWx0LWluXCIse1widHlwZXNcIjoxfV1dXG4lJSBWZXJ0ZXggMTkgaGFzIHVuZGVmaW5lZCBvdXRnb2luZyBlZGdlcy4gZXhwZWN0ZWQ6IHVuZGVmaW5lZCB2cyBnb3Q6IFtbMTcse1widHlwZXNcIjo3Mn1dLFtcImJ1aWx0LWluXCIse1widHlwZXNcIjoxfV1dXG4lJSBWZXJ0ZXggMjQgaGFzIHVuZGVmaW5lZCBvdXRnb2luZyBlZGdlcy4gZXhwZWN0ZWQ6IHVuZGVmaW5lZCB2cyBnb3Q6IFtbMjMse1widHlwZXNcIjo2NH1dLFsyMix7XCJ0eXBlc1wiOjcyfV0sW1wiYnVpbHQtaW5cIix7XCJ0eXBlc1wiOjF9XV1cbiUlIFZlcnRleCAyMiBoYXMgdW5kZWZpbmVkIG91dGdvaW5nIGVkZ2VzLiBleHBlY3RlZDogdW5kZWZpbmVkIHZzIGdvdDogW1syMyx7XCJ0eXBlc1wiOjJ9XSxbMjQse1widHlwZXNcIjoyfV1dXG4lJSBWZXJ0ZXggMjYgaGFzIHVuZGVmaW5lZCBvdXRnb2luZyBlZGdlcy4gZXhwZWN0ZWQ6IHVuZGVmaW5lZCB2cyBnb3Q6IFtbNSx7XCJ0eXBlc1wiOjF9XSxbMjIse1widHlwZXNcIjoxfV1dXG4lJSBWZXJ0ZXggMjggaGFzIHVuZGVmaW5lZCBvdXRnb2luZyBlZGdlcy4gZXhwZWN0ZWQ6IHVuZGVmaW5lZCB2cyBnb3Q6IFtbMjYse1widHlwZXNcIjo3Mn1dLFtcImJ1aWx0LWluXCIse1widHlwZXNcIjoxfV1dXG4lJSBWZXJ0ZXggMjkgaGFzIHVuZGVmaW5lZCBvdXRnb2luZyBlZGdlcy4gZXhwZWN0ZWQ6IHVuZGVmaW5lZCB2cyBnb3Q6IFtbOSx7XCJ0eXBlc1wiOjY0fV0sWzIxLHtcInR5cGVzXCI6NjR9XSxbMjQse1widHlwZXNcIjo2NH1dLFsyOCx7XCJ0eXBlc1wiOjcyfV0sWzE0LHtcInR5cGVzXCI6OH1dLFsxOSx7XCJ0eXBlc1wiOjh9XSxbXCJidWlsdC1pblwiLHtcInR5cGVzXCI6MX1dXVxuJSUgVmVydGV4IDMxIGhhcyB1bmRlZmluZWQgb3V0Z29pbmcgZWRnZXMuIGV4cGVjdGVkOiB1bmRlZmluZWQgdnMgZ290OiBbWzMwLHtcInR5cGVzXCI6NjR9XSxbMCx7XCJ0eXBlc1wiOjcyfV0sW1wiYnVpbHQtaW5cIix7XCJ0eXBlc1wiOjF9XV1cbiUlIFZlcnRleCAwIGhhcyB1bmRlZmluZWQgb3V0Z29pbmcgZWRnZXMuIGV4cGVjdGVkOiB1bmRlZmluZWQgdnMgZ290OiBbWzMwLHtcInR5cGVzXCI6Mn1dLFszMSx7XCJ0eXBlc1wiOjJ9XV1cbiUlIFZlcnRleCAzNSBoYXMgdW5kZWZpbmVkIG91dGdvaW5nIGVkZ2VzLiBleHBlY3RlZDogdW5kZWZpbmVkIHZzIGdvdDogW1szMyx7XCJ0eXBlc1wiOjY0fV0sWzAse1widHlwZXNcIjoxfV0sWzI5LHtcInR5cGVzXCI6OH1dLFszMCx7XCJ0eXBlc1wiOjR9XV1cbiUlIFZlcnRleCAzMyBoYXMgdW5kZWZpbmVkIG91dGdvaW5nIGVkZ2VzLiBleHBlY3RlZDogdW5kZWZpbmVkIHZzIGdvdDogW1sxLHtcInR5cGVzXCI6MTZ9XV1cbiUlIFZlcnRleCAxIGhhcyB1bmRlZmluZWQgb3V0Z29pbmcgZWRnZXMuIGV4cGVjdGVkOiB1bmRlZmluZWQgdnMgZ290OiBbWzMzLHtcInR5cGVzXCI6MzJ9XV1cbmZsb3djaGFydCBURFxuc3ViZ3JhcGggXCJleHBlY3RlZFwiXG5cblxuZW5kXG5zdWJncmFwaCBcImdvdFwiXG5cbiAgICByLWdvdDMwW1wiYCM5MTtSRnVuY3Rpb25EZWZpbml0aW9uIzkzOyBmdW5jdGlvblxuICAgICAgKDMwKVxuICAgICAgKjEuNi0xLjEzKmBcIl1cblxuc3ViZ3JhcGggXCJyLWdvdGZsb3ctMzBcIiBbZnVuY3Rpb24gMzBdXG4gICAgci1nb3QxW1wiYCM5MTtSU3ltYm9sIzkzOyB4XG4gICAgICAoMSlcbiAgICAgICoxLjE1LTEuMTUqYFwiXVxuICAgIHN0eWxlIHItZ290MSBzdHJva2U6YmxhY2ssc3Ryb2tlLXdpZHRoOjdweDsgXG4gICAgci1nb3Q2e3tcImAjOTE7Uk51bWJlciM5MzsgM1xuICAgICAgKDYpXG4gICAgICAqMi45LTIuOSpgXCJ9fVxuICAgIHItZ290NyhbXCJgIzkxO1JTeW1ib2wjOTM7IHhcbiAgICAgICg3KVxuICAgICAgKjIuMTMtMi4xMypgXCJdKVxuICAgIHN0eWxlIHItZ290NyBzdHJva2U6YmxhY2ssc3Ryb2tlLXdpZHRoOjdweDsgXG4gICAgJSUgRW52aXJvbm1lbnQgb2YgOCBbbGV2ZWw6IDFdOlxuICAgICUlIEJ1aWx0LWluXG4gICAgJSUgMTg0OC0tZ2xvYmFsLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLVxuICAgICUlIDE4NDktLWxvY2FsLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLVxuICAgICUlICAgeDoge3ggKDEsIHBhcmFtZXRlciwgZGVmLiBAMil9XG4gICAgci1nb3Q4W1tcImAjOTE7UkJpbmFyeU9wIzkzOyAjNDI7XG4gICAgICAoOClcbiAgICAgICoyLjExLTIuMTEqXG4gICAgKDYsIDcpYFwiXV1cbiAgICBzdHlsZSByLWdvdDggc3Ryb2tlOmJsYWNrLHN0cm9rZS13aWR0aDo3cHg7IFxuICAgIHItZ290NVtcImAjOTE7UlN5bWJvbCM5MzsgeFxuICAgICAgKDUpXG4gICAgICAqMi40LTIuNCpgXCJdXG4gICAgc3R5bGUgci1nb3Q1IHN0cm9rZTpibGFjayxzdHJva2Utd2lkdGg6N3B4OyBcbiAgICAlJSBFbnZpcm9ubWVudCBvZiA5IFtsZXZlbDogMV06XG4gICAgJSUgQnVpbHQtaW5cbiAgICAlJSAxODU4LS1nbG9iYWwtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tXG4gICAgJSUgMTg1OS0tbG9jYWwtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tXG4gICAgJSUgICB4OiB7eCAoMSwgcGFyYW1ldGVyLCBkZWYuIEAyKX1cbiAgICByLWdvdDlbW1wiYCM5MTtSQmluYXJ5T3AjOTM7ICM2MDsjNDU7XG4gICAgICAoOSlcbiAgICAgICoyLjYtMi43KlxuICAgICg1LCA4KWBcIl1dXG4gICAgc3R5bGUgci1nb3Q5IHN0cm9rZTpibGFjayxzdHJva2Utd2lkdGg6N3B4OyBcbiAgICByLWdvdDEwKFtcImAjOTE7UlN5bWJvbCM5Mzsga1xuICAgICAgKDEwKVxuICAgICAgKjMuNy0zLjcqYFwiXSlcbiAgICByLWdvdDEyKFtcImAjOTE7UlN5bWJvbCM5MzsgeFxuICAgICAgKDEyKVxuICAgICAgKjQuMTQtNC4xNCpgXCJdKVxuICAgIHN0eWxlIHItZ290MTIgc3Ryb2tlOmJsYWNrLHN0cm9rZS13aWR0aDo3cHg7IFxuICAgICUlIEVudmlyb25tZW50IG9mIDE0IFtsZXZlbDogMV06XG4gICAgJSUgQnVpbHQtaW5cbiAgICAlJSAxODY3LS1nbG9iYWwtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tXG4gICAgJSUgMTg2OC0tbG9jYWwtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tXG4gICAgJSUgICB4OiB7eCAoNSwgdmFyaWFibGUsIGRlZi4gQDkpfVxuICAgIHItZ290MTRbW1wiYCM5MTtSRnVuY3Rpb25DYWxsIzkzOyByZXR1cm5cbiAgICAgICgxNCwgOm1heWJlOjIxKVxuICAgICAgKjQuNy00LjEyKlxuICAgICgxMilgXCJdXVxuICAgIHN0eWxlIHItZ290MTQgc3Ryb2tlOmJsYWNrLHN0cm9rZS13aWR0aDo3cHg7IFxuICAgIHItZ290MTd7e1wiYCM5MTtSTnVtYmVyIzkzOyAxXG4gICAgICAoMTcpXG4gICAgICAqNi4xNC02LjE0KmBcIn19XG4gICAgJSUgRW52aXJvbm1lbnQgb2YgMTkgW2xldmVsOiAxXTpcbiAgICAlJSBCdWlsdC1pblxuICAgICUlIDE4NzUtLWdsb2JhbC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cbiAgICAlJSAxODc2LS1sb2NhbC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cbiAgICAlJSAgIHg6IHt4ICg1LCB2YXJpYWJsZSwgZGVmLiBAOSl9XG4gICAgci1nb3QxOVtbXCJgIzkxO1JGdW5jdGlvbkNhbGwjOTM7IHJldHVyblxuICAgICAgKDE5LCA6bWF5YmU6MjEpXG4gICAgICAqNi43LTYuMTIqXG4gICAgKDE3KWBcIl1dXG4gICAgc3R5bGUgci1nb3QxOSBzdHJva2U6YmxhY2ssc3Ryb2tlLXdpZHRoOjdweDsgXG4gICAgJSUgRW52aXJvbm1lbnQgb2YgMjEgW2xldmVsOiAxXTpcbiAgICAlJSBCdWlsdC1pblxuICAgICUlIDE4ODEtLWdsb2JhbC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cbiAgICAlJSAxODgyLS1sb2NhbC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cbiAgICAlJSAgIHg6IHt4ICg1LCB2YXJpYWJsZSwgZGVmLiBAOSl9XG4gICAgci1nb3QyMVtbXCJgIzkxO1JJZlRoZW5FbHNlIzkzOyBpZlxuICAgICAgKDIxKVxuICAgICAgKjMuNC0zLjUqXG4gICAgKDEwLCAxNCwgMTkpYFwiXV1cbiAgICBzdHlsZSByLWdvdDIxIHN0cm9rZTpibGFjayxzdHJva2Utd2lkdGg6N3B4OyBcbiAgICByLWdvdDIze3tcImAjOTE7Uk51bWJlciM5MzsgMlxuICAgICAgKDIzKVxuICAgICAgKjcuOS03LjkqYFwifX1cbiAgICByLWdvdDIyW1wiYCM5MTtSU3ltYm9sIzkzOyB4XG4gICAgICAoMjIsIDptYXliZTopXG4gICAgICAqNy40LTcuNCpgXCJdXG4gICAgc3R5bGUgci1nb3QyMiBzdHJva2U6YmxhY2ssc3Ryb2tlLXdpZHRoOjdweDsgXG4gICAgJSUgRW52aXJvbm1lbnQgb2YgMjQgW2xldmVsOiAxXTpcbiAgICAlJSBCdWlsdC1pblxuICAgICUlIDE4OTMtLWdsb2JhbC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cbiAgICAlJSAxODk0LS1sb2NhbC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cbiAgICAlJSAgIHg6IHt4ICg1LCB2YXJpYWJsZSwgZGVmLiBAOSl9XG4gICAgci1nb3QyNFtbXCJgIzkxO1JCaW5hcnlPcCM5MzsgIzYwOyM0NTtcbiAgICAgICgyNCwgOm1heWJlOilcbiAgICAgICo3LjYtNy43KlxuICAgICgyMiwgMjMpYFwiXV1cbiAgICBzdHlsZSByLWdvdDI0IHN0cm9rZTpibGFjayxzdHJva2Utd2lkdGg6N3B4OyBcbiAgICByLWdvdDI2KFtcImAjOTE7UlN5bWJvbCM5MzsgeFxuICAgICAgKDI2KVxuICAgICAgKjguMTEtOC4xMSpgXCJdKVxuICAgIHN0eWxlIHItZ290MjYgc3Ryb2tlOmJsYWNrLHN0cm9rZS13aWR0aDo3cHg7IFxuICAgICUlIEVudmlyb25tZW50IG9mIDI4IFtsZXZlbDogMV06XG4gICAgJSUgQnVpbHQtaW5cbiAgICAlJSAxOTA0LS1nbG9iYWwtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tXG4gICAgJSUgMTkwNS0tbG9jYWwtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tXG4gICAgJSUgICB4OiB7eCAoNSwgdmFyaWFibGUsIGRlZi4gQDkpLCB4ICgyMiwgdmFyaWFibGUsIHt9LCBkZWYuIEAyNCl9XG4gICAgci1nb3QyOFtbXCJgIzkxO1JGdW5jdGlvbkNhbGwjOTM7IHJldHVyblxuICAgICAgKDI4LCA6bWF5YmU6KVxuICAgICAgKjguNC04LjkqXG4gICAgKDI2KWBcIl1dXG4gICAgc3R5bGUgci1nb3QyOCBzdHJva2U6YmxhY2ssc3Ryb2tlLXdpZHRoOjdweDsgXG4gICAgJSUgRW52aXJvbm1lbnQgb2YgMjkgW2xldmVsOiAxXTpcbiAgICAlJSBCdWlsdC1pblxuICAgICUlIDE5MDgtLWdsb2JhbC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cbiAgICAlJSAxOTA5LS1sb2NhbC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cbiAgICAlJSAgIHg6IHt4ICg1LCB2YXJpYWJsZSwgZGVmLiBAOSksIHggKDIyLCB2YXJpYWJsZSwge30sIGRlZi4gQDI0KX1cbiAgICByLWdvdDI5W1tcImAjOTE7UkV4cHJlc3Npb25MaXN0IzkzOyA/P1xuICAgICAgKDI5KVxuICAgICAgKj8/LT8/KlxuICAgICg5LCAyMSwgMjQsIDI4KWBcIl1dXG4gICAgc3R5bGUgci1nb3QyOSBzdHJva2U6YmxhY2ssc3Ryb2tlLXdpZHRoOjdweDsgXG4gICAgci1nb3RidWlsdC1pbltcIkJ1aWx0LWluXCJdXG4gICAgc3R5bGUgci1nb3QxMCBzdHJva2U6cHVycGxlLHN0cm9rZS13aWR0aDo0cHg7IFxuZW5kXG4gICAgci1nb3QwW1wiYCM5MTtSU3ltYm9sIzkzOyBmXG4gICAgICAoMClcbiAgICAgICoxLjEtMS4xKmBcIl1cbiAgICBzdHlsZSByLWdvdDAgc3Ryb2tlOmJsYWNrLHN0cm9rZS13aWR0aDo3cHg7IFxuICAgIHItZ290MzFbW1wiYCM5MTtSQmluYXJ5T3AjOTM7ICM2MDsjNDU7XG4gICAgICAoMzEpXG4gICAgICAqMS4zLTEuNCpcbiAgICAoMCwgMzApYFwiXV1cbiAgICBzdHlsZSByLWdvdDMxIHN0cm9rZTpibGFjayxzdHJva2Utd2lkdGg6N3B4OyBcbiAgICByLWdvdDMze3tcImAjOTE7Uk51bWJlciM5MzsgNVxuICAgICAgKDMzKVxuICAgICAgKjExLjMtMTEuMypgXCJ9fVxuICAgIHN0eWxlIHItZ290MzMgc3Ryb2tlOmJsYWNrLHN0cm9rZS13aWR0aDo3cHg7IFxuICAgICUlIEVudmlyb25tZW50IG9mIDM1IFtsZXZlbDogMF06XG4gICAgJSUgQnVpbHQtaW5cbiAgICAlJSAxOTIyLS1nbG9iYWwtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tXG4gICAgJSUgICBmOiB7ZiAoMCwgZnVuY3Rpb24sIGRlZi4gQDMxKX1cbiAgICByLWdvdDM1W1tcImAjOTE7UkZ1bmN0aW9uQ2FsbCM5MzsgZlxuICAgICAgKDM1KVxuICAgICAgKjExLjEtMTEuMSpcbiAgICAoMzMpYFwiXV1cbiAgICBzdHlsZSByLWdvdDM1IHN0cm9rZTpibGFjayxzdHJva2Utd2lkdGg6N3B4OyBcbiAgICByLWdvdGJ1aWx0LWluW1wiQnVpbHQtaW5cIl1cbiAgICByLWdvdDEgLS0+fFwiZGVmaW5lcy1vbi1jYWxsXCJ8IHItZ290MzNcbiAgICByLWdvdDcgLS0+fFwicmVhZHNcInwgci1nb3QxXG4gICAgci1nb3Q4IC0tPnxcInJlYWRzXCJ8IHItZ290YnVpbHQtaW5cbiAgICByLWdvdDggLS0+fFwicmVhZHMsIGFyZ3VtZW50XCJ8IHItZ290NlxuICAgIHItZ290OCAtLT58XCJyZWFkcywgYXJndW1lbnRcInwgci1nb3Q3XG4gICAgci1nb3Q1IC0tPnxcImRlZmluZWQtYnlcInwgci1nb3Q4XG4gICAgci1nb3Q1IC0tPnxcImRlZmluZWQtYnlcInwgci1nb3Q5XG4gICAgci1nb3Q5IC0tPnxcImFyZ3VtZW50XCJ8IHItZ290OFxuICAgIHItZ290OSAtLT58XCJyZXR1cm5zLCBhcmd1bWVudFwifCByLWdvdDVcbiAgICByLWdvdDkgLS0+fFwicmVhZHNcInwgci1nb3RidWlsdC1pblxuICAgIHItZ290MTIgLS0+fFwicmVhZHNcInwgci1nb3Q1XG4gICAgci1nb3QxNCAtLT58XCJyZXR1cm5zLCBhcmd1bWVudFwifCByLWdvdDEyXG4gICAgci1nb3QxNCAtLT58XCJyZWFkc1wifCByLWdvdGJ1aWx0LWluXG4gICAgci1nb3QxNCAtLT58XCJDRFwifCByLWdvdDIxXG4gICAgbGlua1N0eWxlIDEzIHN0cm9rZTpncmF5LGNvbG9yOmdyYXk7XG4gICAgci1nb3QxOSAtLT58XCJyZXR1cm5zLCBhcmd1bWVudFwifCByLWdvdDE3XG4gICAgci1nb3QxOSAtLT58XCJyZWFkc1wifCByLWdvdGJ1aWx0LWluXG4gICAgci1nb3QxOSAtLT58XCJDRFwifCByLWdvdDIxXG4gICAgbGlua1N0eWxlIDE2IHN0cm9rZTpncmF5LGNvbG9yOmdyYXk7XG4gICAgci1nb3QyMSAtLT58XCJyZXR1cm5zLCBhcmd1bWVudFwifCByLWdvdDE0XG4gICAgci1nb3QyMSAtLT58XCJyZXR1cm5zLCBhcmd1bWVudFwifCByLWdvdDE5XG4gICAgci1nb3QyMSAtLT58XCJyZWFkcywgYXJndW1lbnRcInwgci1nb3QxMFxuICAgIHItZ290MjEgLS0+fFwicmVhZHNcInwgci1nb3RidWlsdC1pblxuICAgIHItZ290MjIgLS0+fFwiZGVmaW5lZC1ieVwifCByLWdvdDIzXG4gICAgci1nb3QyMiAtLT58XCJkZWZpbmVkLWJ5XCJ8IHItZ290MjRcbiAgICByLWdvdDI0IC0tPnxcImFyZ3VtZW50XCJ8IHItZ290MjNcbiAgICByLWdvdDI0IC0tPnxcInJldHVybnMsIGFyZ3VtZW50XCJ8IHItZ290MjJcbiAgICByLWdvdDI0IC0tPnxcInJlYWRzXCJ8IHItZ290YnVpbHQtaW5cbiAgICByLWdvdDI2IC0tPnxcInJlYWRzXCJ8IHItZ290NVxuICAgIHItZ290MjYgLS0+fFwicmVhZHNcInwgci1nb3QyMlxuICAgIHItZ290MjggLS0+fFwicmV0dXJucywgYXJndW1lbnRcInwgci1nb3QyNlxuICAgIHItZ290MjggLS0+fFwicmVhZHNcInwgci1nb3RidWlsdC1pblxuICAgIHItZ290MjkgLS0+fFwiYXJndW1lbnRcInwgci1nb3Q5XG4gICAgci1nb3QyOSAtLT58XCJhcmd1bWVudFwifCByLWdvdDIxXG4gICAgci1nb3QyOSAtLT58XCJhcmd1bWVudFwifCByLWdvdDI0XG4gICAgci1nb3QyOSAtLT58XCJyZXR1cm5zLCBhcmd1bWVudFwifCByLWdvdDI4XG4gICAgci1nb3QyOSAtLT58XCJyZXR1cm5zXCJ8IHItZ290MTRcbiAgICByLWdvdDI5IC0tPnxcInJldHVybnNcInwgci1nb3QxOVxuICAgIHItZ290MjkgLS0+fFwicmVhZHNcInwgci1nb3RidWlsdC1pblxuci1nb3QzMCAtLi18ZnVuY3Rpb258IHItZ290Zmxvdy0zMFxuXG4gICAgci1nb3QwIC0tPnxcImRlZmluZWQtYnlcInwgci1nb3QzMFxuICAgIHItZ290MCAtLT58XCJkZWZpbmVkLWJ5XCJ8IHItZ290MzFcbiAgICByLWdvdDMxIC0tPnxcImFyZ3VtZW50XCJ8IHItZ290MzBcbiAgICByLWdvdDMxIC0tPnxcInJldHVybnMsIGFyZ3VtZW50XCJ8IHItZ290MFxuICAgIHItZ290MzEgLS0+fFwicmVhZHNcInwgci1nb3RidWlsdC1pblxuICAgIHItZ290MzMgLS0+fFwiZGVmaW5lZC1ieS1vbi1jYWxsXCJ8IHItZ290MVxuICAgIHItZ290MzUgLS0+fFwiYXJndW1lbnRcInwgci1nb3QzM1xuICAgIHItZ290MzUgLS0+fFwicmVhZHNcInwgci1nb3QwXG4gICAgci1nb3QzNSAtLT58XCJyZXR1cm5zXCJ8IHItZ290MjlcbiAgICByLWdvdDM1IC0tPnxcImNhbGxzXCJ8IHItZ290MzBcbmVuZCIsIm1lcm1haWQiOnsiYXV0b1N5bmMiOnRydWV9fQ==
). The assignment of `x <- 2` is still contained in it, even though it should be considered dead code. 

Dead code detection works correctly, however, when a return *always* occurs (ie outside of an if/else block), like in this example:
```R
f <- function(x) {
   x <- 3 * x
   return(x)
   x <- 2
   return(x)
}

f(5)
```

Both of these tests are included in #800.

**Comment by Ellpeck** [comment]
This also occurs when slicing, see this test:
```ts
		assertSliced(label('dead code (return in if)', []),
			shell, `f <- function(x) {
   x <- 3 * x
   if(k)
      return(x)
   else
      return(1)
   # alles drunter soll natürlich weg 
   x <- 2
   return(x)
}

f(5)`, ['12@f'], `f <- function(x) {
        x <- 3 * x
        if(k) return(x) else
        return(1)
        x <- 2
        return(x)
    }
f(5)`)
```

**Comment by EagleoutIce** [comment]
This is no fixed by the linked PR, please still include the tests as part of #800.
