### ISSUE TITLE
Claims don't match tests for some labels

### ISSUE THREAD

**Issue by Ellpeck** [Code-Inspect/flowr#820]
Notably, the labels `built-in-sequencing` and `accessing-internal-names` have the unsupported claim, but various tests that claim to include them.

**Comment by EagleoutIce** [comment]
Can you be more specific please? Are these the only ones?

**Comment by Ellpeck** [comment]
Yes, it appears that way. Here are their reports:

```
    [1/2/9] Accessing Internal Names (claim: not supported) is covered by 1 test:
          - desugar [1]: #304

      [2/1/10/3] Sequencing (claim: not supported) is covered by 22 tests:
            - dataflow [5]: #69-#70, #99, #119-#120
            - desugar [7]: #400-#404, #490-#491
            - slice [10]: #647, #653-#654, #660-#666
            - output [2]: #647, #660
```

**Comment by EagleoutIce** [comment]
So, the access of internal names label should be removed as we just use the `:::` token and not really resolve anything there. Sequencing on the other hand should be updated like this:
1) the description in `data.ts` should state that this refers to the abstract interpretation support (i.e., contributing information on the value domain). Consequently, the label should be removed from all tests exposing it (or in other words, we treat it as a simple binary operator). Can you do that? @Ellpeck
